[tasks.install]
script = [
    "cargo install wasm-pack",
    "npm install",
    "cargo install tauri-bundler"
]

[tasks.build-yew]
script = [
    "cd src-yew",
    "rm -rf ../dist",
    "wasm-pack build --release --no-typescript --target web --out-name wasm -d ../dist",
    "cp static/* ../dist/"
]

[tasks.clean-yew]
script = [
    "cd src-yew",
    "cargo clean"
]

[tasks.build-tauri]
script = [
    "npm run tauri build"
]

[tasks.clean-tauri]
script = [
    "cd src-tauri",
    "cargo clean"
]

[tasks.deploy]
dependencies = [
    "install",
    "build-yew",
    "build-tauri",
]

[tasks.clean]
dependencies = [
    "clean-yew",
    "clean-tauri",
]

[tasks.run]
command = "src-tauri/target/release/tauri-app"
dependencies = ["deploy"]
